// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PutScoreRequest_TeamType int32

const (
	PutScoreRequest_Home    PutScoreRequest_TeamType = 0
	PutScoreRequest_Visitor PutScoreRequest_TeamType = 1
)

var PutScoreRequest_TeamType_name = map[int32]string{
	0: "Home",
	1: "Visitor",
}

var PutScoreRequest_TeamType_value = map[string]int32{
	"Home":    0,
	"Visitor": 1,
}

func (x PutScoreRequest_TeamType) String() string {
	return proto.EnumName(PutScoreRequest_TeamType_name, int32(x))
}

func (PutScoreRequest_TeamType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{4, 0}
}

// General
type GeneralRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeneralRequest) Reset()         { *m = GeneralRequest{} }
func (m *GeneralRequest) String() string { return proto.CompactTextString(m) }
func (*GeneralRequest) ProtoMessage()    {}
func (*GeneralRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{0}
}

func (m *GeneralRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneralRequest.Unmarshal(m, b)
}
func (m *GeneralRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneralRequest.Marshal(b, m, deterministic)
}
func (m *GeneralRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneralRequest.Merge(m, src)
}
func (m *GeneralRequest) XXX_Size() int {
	return xxx_messageInfo_GeneralRequest.Size(m)
}
func (m *GeneralRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneralRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GeneralRequest proto.InternalMessageInfo

type GeneralReply struct {
	Result               string   `protobuf:"bytes,1,opt,name=Result,json=result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeneralReply) Reset()         { *m = GeneralReply{} }
func (m *GeneralReply) String() string { return proto.CompactTextString(m) }
func (*GeneralReply) ProtoMessage()    {}
func (*GeneralReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{1}
}

func (m *GeneralReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneralReply.Unmarshal(m, b)
}
func (m *GeneralReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneralReply.Marshal(b, m, deterministic)
}
func (m *GeneralReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneralReply.Merge(m, src)
}
func (m *GeneralReply) XXX_Size() int {
	return xxx_messageInfo_GeneralReply.Size(m)
}
func (m *GeneralReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneralReply.DiscardUnknown(m)
}

var xxx_messageInfo_GeneralReply proto.InternalMessageInfo

func (m *GeneralReply) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

// GetScore
type GetScoreRequest struct {
	Game                 string   `protobuf:"bytes,1,opt,name=Game,json=game,proto3" json:"Game,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetScoreRequest) Reset()         { *m = GetScoreRequest{} }
func (m *GetScoreRequest) String() string { return proto.CompactTextString(m) }
func (*GetScoreRequest) ProtoMessage()    {}
func (*GetScoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{2}
}

func (m *GetScoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetScoreRequest.Unmarshal(m, b)
}
func (m *GetScoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetScoreRequest.Marshal(b, m, deterministic)
}
func (m *GetScoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetScoreRequest.Merge(m, src)
}
func (m *GetScoreRequest) XXX_Size() int {
	return xxx_messageInfo_GetScoreRequest.Size(m)
}
func (m *GetScoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetScoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetScoreRequest proto.InternalMessageInfo

func (m *GetScoreRequest) GetGame() string {
	if m != nil {
		return m.Game
	}
	return ""
}

type GetScoreReply struct {
	Home                 []int32  `protobuf:"varint,1,rep,packed,name=Home,json=home,proto3" json:"Home,omitempty"`
	HomeTotal            int32    `protobuf:"varint,2,opt,name=HomeTotal,json=homeTotal,proto3" json:"HomeTotal,omitempty"`
	Visitor              []int32  `protobuf:"varint,3,rep,packed,name=Visitor,json=visitor,proto3" json:"Visitor,omitempty"`
	VisitorTotal         int32    `protobuf:"varint,4,opt,name=VisitorTotal,json=visitorTotal,proto3" json:"VisitorTotal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetScoreReply) Reset()         { *m = GetScoreReply{} }
func (m *GetScoreReply) String() string { return proto.CompactTextString(m) }
func (*GetScoreReply) ProtoMessage()    {}
func (*GetScoreReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{3}
}

func (m *GetScoreReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetScoreReply.Unmarshal(m, b)
}
func (m *GetScoreReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetScoreReply.Marshal(b, m, deterministic)
}
func (m *GetScoreReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetScoreReply.Merge(m, src)
}
func (m *GetScoreReply) XXX_Size() int {
	return xxx_messageInfo_GetScoreReply.Size(m)
}
func (m *GetScoreReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetScoreReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetScoreReply proto.InternalMessageInfo

func (m *GetScoreReply) GetHome() []int32 {
	if m != nil {
		return m.Home
	}
	return nil
}

func (m *GetScoreReply) GetHomeTotal() int32 {
	if m != nil {
		return m.HomeTotal
	}
	return 0
}

func (m *GetScoreReply) GetVisitor() []int32 {
	if m != nil {
		return m.Visitor
	}
	return nil
}

func (m *GetScoreReply) GetVisitorTotal() int32 {
	if m != nil {
		return m.VisitorTotal
	}
	return 0
}

// PutScore
type PutScoreRequest struct {
	Game                 string                   `protobuf:"bytes,1,opt,name=Game,json=game,proto3" json:"Game,omitempty"`
	Team                 PutScoreRequest_TeamType `protobuf:"varint,2,opt,name=Team,json=team,proto3,enum=pb.PutScoreRequest_TeamType" json:"Team,omitempty"`
	Round                int32                    `protobuf:"varint,3,opt,name=Round,json=round,proto3" json:"Round,omitempty"`
	Add                  int32                    `protobuf:"varint,4,opt,name=Add,json=add,proto3" json:"Add,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *PutScoreRequest) Reset()         { *m = PutScoreRequest{} }
func (m *PutScoreRequest) String() string { return proto.CompactTextString(m) }
func (*PutScoreRequest) ProtoMessage()    {}
func (*PutScoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{4}
}

func (m *PutScoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutScoreRequest.Unmarshal(m, b)
}
func (m *PutScoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutScoreRequest.Marshal(b, m, deterministic)
}
func (m *PutScoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutScoreRequest.Merge(m, src)
}
func (m *PutScoreRequest) XXX_Size() int {
	return xxx_messageInfo_PutScoreRequest.Size(m)
}
func (m *PutScoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutScoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutScoreRequest proto.InternalMessageInfo

func (m *PutScoreRequest) GetGame() string {
	if m != nil {
		return m.Game
	}
	return ""
}

func (m *PutScoreRequest) GetTeam() PutScoreRequest_TeamType {
	if m != nil {
		return m.Team
	}
	return PutScoreRequest_Home
}

func (m *PutScoreRequest) GetRound() int32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *PutScoreRequest) GetAdd() int32 {
	if m != nil {
		return m.Add
	}
	return 0
}

// GetGameList
type GetGameListReply struct {
	Game                 []string `protobuf:"bytes,1,rep,name=Game,json=game,proto3" json:"Game,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGameListReply) Reset()         { *m = GetGameListReply{} }
func (m *GetGameListReply) String() string { return proto.CompactTextString(m) }
func (*GetGameListReply) ProtoMessage()    {}
func (*GetGameListReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{5}
}

func (m *GetGameListReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGameListReply.Unmarshal(m, b)
}
func (m *GetGameListReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGameListReply.Marshal(b, m, deterministic)
}
func (m *GetGameListReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGameListReply.Merge(m, src)
}
func (m *GetGameListReply) XXX_Size() int {
	return xxx_messageInfo_GetGameListReply.Size(m)
}
func (m *GetGameListReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGameListReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetGameListReply proto.InternalMessageInfo

func (m *GetGameListReply) GetGame() []string {
	if m != nil {
		return m.Game
	}
	return nil
}

// PostNewGame
type PostNewGameRequest struct {
	Game                 string   `protobuf:"bytes,1,opt,name=Game,json=game,proto3" json:"Game,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostNewGameRequest) Reset()         { *m = PostNewGameRequest{} }
func (m *PostNewGameRequest) String() string { return proto.CompactTextString(m) }
func (*PostNewGameRequest) ProtoMessage()    {}
func (*PostNewGameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{6}
}

func (m *PostNewGameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostNewGameRequest.Unmarshal(m, b)
}
func (m *PostNewGameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostNewGameRequest.Marshal(b, m, deterministic)
}
func (m *PostNewGameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostNewGameRequest.Merge(m, src)
}
func (m *PostNewGameRequest) XXX_Size() int {
	return xxx_messageInfo_PostNewGameRequest.Size(m)
}
func (m *PostNewGameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostNewGameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostNewGameRequest proto.InternalMessageInfo

func (m *PostNewGameRequest) GetGame() string {
	if m != nil {
		return m.Game
	}
	return ""
}

func init() {
	proto.RegisterEnum("pb.PutScoreRequest_TeamType", PutScoreRequest_TeamType_name, PutScoreRequest_TeamType_value)
	proto.RegisterType((*GeneralRequest)(nil), "pb.GeneralRequest")
	proto.RegisterType((*GeneralReply)(nil), "pb.GeneralReply")
	proto.RegisterType((*GetScoreRequest)(nil), "pb.GetScoreRequest")
	proto.RegisterType((*GetScoreReply)(nil), "pb.GetScoreReply")
	proto.RegisterType((*PutScoreRequest)(nil), "pb.PutScoreRequest")
	proto.RegisterType((*GetGameListReply)(nil), "pb.GetGameListReply")
	proto.RegisterType((*PostNewGameRequest)(nil), "pb.PostNewGameRequest")
}

func init() { proto.RegisterFile("game.proto", fileDescriptor_38fc58335341d769) }

var fileDescriptor_38fc58335341d769 = []byte{
	// 390 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xbf, 0x8e, 0xd3, 0x40,
	0x10, 0xc6, 0xe3, 0xb3, 0x9d, 0x73, 0xe6, 0x72, 0x77, 0x66, 0x88, 0x22, 0x2b, 0x4a, 0x11, 0x56,
	0x22, 0x72, 0x65, 0xa1, 0x84, 0x86, 0x92, 0xca, 0x14, 0x08, 0x45, 0x4e, 0x44, 0xef, 0xc4, 0x23,
	0x62, 0xc9, 0xce, 0x9a, 0xf5, 0x3a, 0x28, 0x15, 0xef, 0xc2, 0x13, 0xf2, 0x08, 0x68, 0xd7, 0x7f,
	0xf2, 0x07, 0xc4, 0x55, 0xd6, 0x7e, 0x33, 0x3f, 0x7f, 0xf3, 0xcd, 0x2e, 0xc0, 0xb7, 0x38, 0xa7,
	0xa0, 0x10, 0x5c, 0x72, 0xbc, 0x2b, 0xb6, 0xcc, 0x85, 0xa7, 0x90, 0x0e, 0x24, 0xe2, 0x2c, 0xa2,
	0xef, 0x15, 0x95, 0x92, 0xcd, 0x61, 0xd8, 0x29, 0x45, 0x76, 0xc2, 0x31, 0xf4, 0x23, 0x2a, 0xab,
	0x4c, 0x7a, 0xc6, 0xcc, 0xf0, 0x07, 0x51, 0x5f, 0xe8, 0x13, 0x7b, 0x0b, 0xcf, 0x21, 0xc9, 0xf5,
	0x8e, 0x0b, 0x6a, 0x50, 0x44, 0xb0, 0xc2, 0x38, 0xa7, 0xa6, 0xd1, 0x52, 0x56, 0xec, 0x27, 0x3c,
	0x9e, 0xdb, 0xd4, 0xff, 0x10, 0xac, 0x4f, 0x5c, 0x37, 0x99, 0xbe, 0x1d, 0x59, 0x7b, 0x9e, 0x13,
	0x4e, 0x61, 0xa0, 0xb4, 0x0d, 0x97, 0x71, 0xe6, 0xdd, 0xcd, 0x0c, 0xdf, 0x8e, 0x06, 0xfb, 0x56,
	0x40, 0x0f, 0xee, 0xbf, 0xa6, 0x65, 0x2a, 0xb9, 0xf0, 0x4c, 0x0d, 0xdd, 0x1f, 0xeb, 0x23, 0x32,
	0x18, 0x36, 0x95, 0x1a, 0xb5, 0x34, 0x3a, 0x3c, 0x5e, 0x68, 0xec, 0x97, 0x01, 0xcf, 0xab, 0xea,
	0xc5, 0x41, 0xf1, 0x1d, 0x58, 0x1b, 0x8a, 0x73, 0x6d, 0xff, 0xb4, 0x98, 0x06, 0xc5, 0x36, 0xb8,
	0xc1, 0x02, 0x55, 0xdf, 0x9c, 0x0a, 0x8a, 0x2c, 0x49, 0x71, 0x8e, 0x23, 0xb0, 0x23, 0x5e, 0x1d,
	0x12, 0xcf, 0xd4, 0xb6, 0xb6, 0x50, 0x07, 0x74, 0xc1, 0xfc, 0x98, 0x24, 0xcd, 0x28, 0x66, 0x9c,
	0x24, 0xec, 0x0d, 0x38, 0x2d, 0x89, 0x4e, 0x9d, 0xde, 0xed, 0xe1, 0x43, 0x97, 0xca, 0x35, 0xd8,
	0x1c, 0xdc, 0x90, 0xa4, 0x9a, 0xe9, 0x73, 0x5a, 0xca, 0x6e, 0x51, 0xcd, 0x90, 0x66, 0xb7, 0x4d,
	0x1f, 0x70, 0xc5, 0x4b, 0xf9, 0x85, 0x7e, 0xa8, 0xd2, 0x7f, 0xe2, 0x2c, 0x7e, 0x1b, 0xf0, 0xb8,
	0x26, 0x71, 0x4c, 0x77, 0xa4, 0x3e, 0x24, 0xf0, 0x3d, 0x38, 0xed, 0x4d, 0xe0, 0x6b, 0x15, 0xef,
	0xe6, 0xfa, 0x26, 0xaf, 0xae, 0xc5, 0x22, 0x3b, 0xb1, 0x1e, 0x2e, 0xc1, 0x69, 0xd7, 0x50, 0x53,
	0x37, 0x4b, 0x99, 0xb8, 0x35, 0x75, 0x7e, 0x31, 0xac, 0x87, 0x1f, 0xe0, 0xe1, 0x22, 0x0e, 0xe2,
	0x55, 0x4b, 0x8d, 0x8d, 0x1a, 0xb3, 0xab, 0xcc, 0x35, 0x7a, 0x91, 0x10, 0xc7, 0xda, 0xf2, 0xaf,
	0xc8, 0xff, 0x72, 0xdd, 0xf6, 0xf5, 0xb3, 0x5e, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0xc7, 0x44,
	0x3f, 0x3f, 0xe4, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServiceServerClient is the client API for ServiceServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceServerClient interface {
	GetScore(ctx context.Context, in *GetScoreRequest, opts ...grpc.CallOption) (*GetScoreReply, error)
	PutScore(ctx context.Context, in *PutScoreRequest, opts ...grpc.CallOption) (*GeneralReply, error)
	GetGameList(ctx context.Context, in *GeneralRequest, opts ...grpc.CallOption) (*GetGameListReply, error)
	PostNewGame(ctx context.Context, in *PostNewGameRequest, opts ...grpc.CallOption) (*GeneralReply, error)
}

type serviceServerClient struct {
	cc *grpc.ClientConn
}

func NewServiceServerClient(cc *grpc.ClientConn) ServiceServerClient {
	return &serviceServerClient{cc}
}

func (c *serviceServerClient) GetScore(ctx context.Context, in *GetScoreRequest, opts ...grpc.CallOption) (*GetScoreReply, error) {
	out := new(GetScoreReply)
	err := c.cc.Invoke(ctx, "/pb.ServiceServer/GetScore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceServerClient) PutScore(ctx context.Context, in *PutScoreRequest, opts ...grpc.CallOption) (*GeneralReply, error) {
	out := new(GeneralReply)
	err := c.cc.Invoke(ctx, "/pb.ServiceServer/PutScore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceServerClient) GetGameList(ctx context.Context, in *GeneralRequest, opts ...grpc.CallOption) (*GetGameListReply, error) {
	out := new(GetGameListReply)
	err := c.cc.Invoke(ctx, "/pb.ServiceServer/GetGameList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceServerClient) PostNewGame(ctx context.Context, in *PostNewGameRequest, opts ...grpc.CallOption) (*GeneralReply, error) {
	out := new(GeneralReply)
	err := c.cc.Invoke(ctx, "/pb.ServiceServer/PostNewGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServerServer is the server API for ServiceServer service.
type ServiceServerServer interface {
	GetScore(context.Context, *GetScoreRequest) (*GetScoreReply, error)
	PutScore(context.Context, *PutScoreRequest) (*GeneralReply, error)
	GetGameList(context.Context, *GeneralRequest) (*GetGameListReply, error)
	PostNewGame(context.Context, *PostNewGameRequest) (*GeneralReply, error)
}

// UnimplementedServiceServerServer can be embedded to have forward compatible implementations.
type UnimplementedServiceServerServer struct {
}

func (*UnimplementedServiceServerServer) GetScore(ctx context.Context, req *GetScoreRequest) (*GetScoreReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScore not implemented")
}
func (*UnimplementedServiceServerServer) PutScore(ctx context.Context, req *PutScoreRequest) (*GeneralReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutScore not implemented")
}
func (*UnimplementedServiceServerServer) GetGameList(ctx context.Context, req *GeneralRequest) (*GetGameListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGameList not implemented")
}
func (*UnimplementedServiceServerServer) PostNewGame(ctx context.Context, req *PostNewGameRequest) (*GeneralReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostNewGame not implemented")
}

func RegisterServiceServerServer(s *grpc.Server, srv ServiceServerServer) {
	s.RegisterService(&_ServiceServer_serviceDesc, srv)
}

func _ServiceServer_GetScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServerServer).GetScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ServiceServer/GetScore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServerServer).GetScore(ctx, req.(*GetScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceServer_PutScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServerServer).PutScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ServiceServer/PutScore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServerServer).PutScore(ctx, req.(*PutScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceServer_GetGameList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneralRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServerServer).GetGameList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ServiceServer/GetGameList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServerServer).GetGameList(ctx, req.(*GeneralRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceServer_PostNewGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostNewGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServerServer).PostNewGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ServiceServer/PostNewGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServerServer).PostNewGame(ctx, req.(*PostNewGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServiceServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ServiceServer",
	HandlerType: (*ServiceServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetScore",
			Handler:    _ServiceServer_GetScore_Handler,
		},
		{
			MethodName: "PutScore",
			Handler:    _ServiceServer_PutScore_Handler,
		},
		{
			MethodName: "GetGameList",
			Handler:    _ServiceServer_GetGameList_Handler,
		},
		{
			MethodName: "PostNewGame",
			Handler:    _ServiceServer_PostNewGame_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "game.proto",
}
